/**
 * `oxp protocol-register` — register the `oxp://` URL scheme so clicks
 * in the browser open `oxp install --from <url>` automatically.
 *
 * Per-OS strategy:
 *
 *   macOS    Generate a tiny `.app` bundle at
 *            `~/Applications/OXP Helper.app` whose Info.plist declares
 *            the `oxp` scheme. Its main binary is a shell script that
 *            runs `oxp install --from "$1"`. Then ask Launch Services
 *            to register it.
 *
 *   Linux    Drop a `.desktop` file in
 *            `~/.local/share/applications/oxp-handler.desktop` with
 *            `MimeType=x-scheme-handler/oxp;` and run `xdg-mime default`.
 *
 *   Windows  Write registry keys under `HKCU\Software\Classes\oxp`
 *            pointing at the `oxp.cmd` shim.
 *
 * The command is **idempotent**: running it twice is safe and silent.
 * It's also reversible — `oxp protocol-register --uninstall` removes
 * everything it created.
 *
 * No network calls, no admin/sudo prompt. The handler simply re-invokes
 * the user's installed `oxp` binary, so security stays inside the
 * existing install pipeline (signature, TOFU, permission prompt).
 */

import { promises as fs } from "node:fs";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { homedir, platform } from "node:os";
import { join } from "node:path";

import { fail, info } from "../util.js";

const exec = promisify(execFile);

const MAC_APP_NAME = "OXP Helper.app";
const LINUX_DESKTOP_NAME = "oxp-handler.desktop";

interface ParsedArgs {
  uninstall: boolean;
  oxpBin?: string;
}

const HELP = `oxp protocol-register     Register the oxp:// URL scheme on this machine

Flags:
  --uninstall         Remove the registration
  --oxp-bin <path>    Path to the oxp binary to invoke (default: detected)
`;

function parseArgs(args: string[]): ParsedArgs {
  let uninstall = false;
  let oxpBin: string | undefined;
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === undefined) continue;
    if (a === "--uninstall") uninstall = true;
    else if (a === "--oxp-bin") {
      oxpBin = args[++i];
      if (!oxpBin) fail("--oxp-bin requires a path");
    } else if (a.startsWith("--oxp-bin=")) {
      oxpBin = a.slice("--oxp-bin=".length);
    } else if (a === "-h" || a === "--help") {
      process.stdout.write(HELP);
      process.exit(0);
    } else fail(`unknown flag: ${a}`);
  }
  return { uninstall, oxpBin };
}

export async function protocolRegister(args: string[]): Promise<number> {
  const opts = parseArgs(args);
  const bin = opts.oxpBin ?? (await detectOxpBin());
  if (!bin) fail("could not locate oxp binary — pass --oxp-bin <path>");

  switch (platform()) {
    case "darwin":
      return opts.uninstall ? unregisterMac() : registerMac(bin);
    case "linux":
      return opts.uninstall ? unregisterLinux() : registerLinux(bin);
    case "win32":
      return opts.uninstall ? unregisterWindows() : registerWindows(bin);
    default:
      fail(`unsupported platform: ${platform()}`);
  }
}

async function detectOxpBin(): Promise<string | undefined> {
  // The CLI is most often launched via npx / pnpm dlx, which puts a
  // shim on PATH. Prefer that. Fall back to argv[0] (process.execPath)
  // when nothing matches.
  try {
    const { stdout } = await exec(
      platform() === "win32" ? "where" : "command",
      platform() === "win32" ? ["oxp"] : ["-v", "oxp"],
      { shell: platform() !== "win32", timeout: 1500 },
    );
    const first = stdout.split(/\r?\n/).find((s) => s.trim().length > 0);
    if (first?.trim()) return first.trim();
  } catch {
    // ignore
  }
  return process.execPath;
}

/* -------------------------------------------------------------------------- */
/* macOS                                                                      */
/* -------------------------------------------------------------------------- */

async function registerMac(oxpBin: string): Promise<number> {
  const root = join(homedir(), "Applications", MAC_APP_NAME);
  const contents = join(root, "Contents");
  const macOS = join(contents, "MacOS");
  await fs.mkdir(macOS, { recursive: true });

  const launcher = join(macOS, "oxp-helper");
  const script =
    "#!/bin/sh\n" +
    "# OXP url scheme handler. Auto-generated by `oxp protocol-register`.\n" +
    `exec ${shQuote(oxpBin)} install --from "$1"\n`;
  await fs.writeFile(launcher, script, { mode: 0o755 });

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>            <string>OXP Helper</string>
  <key>CFBundleIdentifier</key>      <string>dev.oxp.helper</string>
  <key>CFBundleVersion</key>         <string>1</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key>     <string>APPL</string>
  <key>CFBundleExecutable</key>      <string>oxp-helper</string>
  <key>LSUIElement</key>             <true/>
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key>     <string>OXP Install</string>
      <key>CFBundleURLSchemes</key>
      <array><string>oxp</string></array>
    </dict>
  </array>
</dict>
</plist>
`;
  await fs.writeFile(join(contents, "Info.plist"), plist);

  // Tell Launch Services to (re)scan the bundle so the URL scheme takes
  // effect immediately. Failure here isn't fatal — the OS will pick the
  // app up on next login.
  try {
    await exec(
      "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister",
      ["-f", root],
      { timeout: 5000 },
    );
  } catch {
    // ignore
  }

  info(`✓ registered oxp:// scheme via ${root}`);
  info(`  test: open 'oxp://install/@oxprotocol/example'`);
  return 0;
}

async function unregisterMac(): Promise<number> {
  const root = join(homedir(), "Applications", MAC_APP_NAME);
  await fs.rm(root, { recursive: true, force: true });
  info(`✓ removed ${root}`);
  return 0;
}

/* -------------------------------------------------------------------------- */
/* Linux                                                                      */
/* -------------------------------------------------------------------------- */

async function registerLinux(oxpBin: string): Promise<number> {
  const dir = join(
    process.env.XDG_DATA_HOME ?? join(homedir(), ".local", "share"),
    "applications",
  );
  await fs.mkdir(dir, { recursive: true });
  const file = join(dir, LINUX_DESKTOP_NAME);

  const desktop =
    "[Desktop Entry]\n" +
    "Type=Application\n" +
    "Name=OXP Install Helper\n" +
    `Exec=${shQuote(oxpBin)} install --from %u\n` +
    "NoDisplay=true\n" +
    "MimeType=x-scheme-handler/oxp;\n" +
    "Categories=Development;\n" +
    "Terminal=false\n";
  await fs.writeFile(file, desktop);

  try {
    await exec("update-desktop-database", [dir], { timeout: 5000 });
  } catch {
    // not all distros ship update-desktop-database; that's fine
  }
  try {
    await exec(
      "xdg-mime",
      ["default", LINUX_DESKTOP_NAME, "x-scheme-handler/oxp"],
      { timeout: 5000 },
    );
  } catch {
    info(`note: xdg-mime not available — install xdg-utils to finalize`);
  }

  info(`✓ registered oxp:// scheme via ${file}`);
  return 0;
}

async function unregisterLinux(): Promise<number> {
  const dir = join(
    process.env.XDG_DATA_HOME ?? join(homedir(), ".local", "share"),
    "applications",
  );
  const file = join(dir, LINUX_DESKTOP_NAME);
  await fs.rm(file, { force: true });
  info(`✓ removed ${file}`);
  return 0;
}

/* -------------------------------------------------------------------------- */
/* Windows                                                                    */
/* -------------------------------------------------------------------------- */

async function registerWindows(oxpBin: string): Promise<number> {
  // Use `reg add` rather than touching the registry via FFI — it's
  // built in and supports HKCU writes without elevation.
  const cmd = `"${oxpBin}" install --from "%1"`;
  const ops: Array<[string, string, string, string]> = [
    ["HKCU\\Software\\Classes\\oxp", "", "REG_SZ", "URL:OXP Install Protocol"],
    ["HKCU\\Software\\Classes\\oxp", "URL Protocol", "REG_SZ", ""],
    ["HKCU\\Software\\Classes\\oxp\\shell\\open\\command", "", "REG_SZ", cmd],
  ];
  for (const [key, name, type, value] of ops) {
    const args = ["add", key];
    if (name) args.push("/v", name);
    else args.push("/ve");
    args.push("/t", type, "/d", value, "/f");
    await exec("reg", args, { timeout: 5000 });
  }
  info(`✓ registered oxp:// scheme in HKCU\\Software\\Classes\\oxp`);
  return 0;
}

async function unregisterWindows(): Promise<number> {
  await exec("reg", ["delete", "HKCU\\Software\\Classes\\oxp", "/f"], {
    timeout: 5000,
  });
  info(`✓ removed HKCU\\Software\\Classes\\oxp`);
  return 0;
}

/* -------------------------------------------------------------------------- */
/* helpers                                                                    */
/* -------------------------------------------------------------------------- */

function shQuote(s: string): string {
  // Just enough to survive paths with spaces — we control the input.
  return `"${s.replace(/"/g, '\\"')}"`;
}
