import * as vscode from "vscode";
import * as fsSync from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import {
  resolveAndVerify,
  Store,
  Grants,
  RuntimeManager,
  VerifyError,
  kindOf,
  finishInstallWithConsent,
  type InstalledRecord,
  type PermissionPromptFn,
  type PermissionPromptItem,
} from "@oxprotocol/host-core";
import { jcoBackend } from "@oxprotocol/host-runtime";
import { vscodeHostFs } from "./fs-adapter";
import { devCommand } from "./dev";
import {
  OxpDevView,
  startDevSession,
  stopDevSession,
  showDevOutput,
  pickAndRunExtensionCommand,
  findOxpProjects,
  autostartEdhIfMarked,
} from "./dev-session";
import { renderMainUi } from "./render";
import { vscodeProviderFactory } from "./runtime-provider";
import { RuntimeRpcService } from "./runtime-rpc-service";
import { ExtensionUiPanel } from "./extension-ui-panel";
import { RuntimePanel } from "./runtime-panel";
import { createBridgeHandler, loadBridgeScript } from "./bridge-handler";
import { extractPermissionStrings } from "./permissions";
import { WrapperWebviewProvider } from "./wrapper-provider";
import { SwitchboardView } from "./switchboard";
import { ExplorerSlotManager, SLOT_PREFIX } from "./explorer-slots";

/**
 * Public API exported by this extension. Wrapper VSIXes (generated by
 * `oxp install` for each installed OXP extension) acquire this API to
 * obtain a bridge-wired `WebviewViewProvider` for their declared view.
 *
 * Each wrapper is a thin, generated extension whose only job is to
 * register an Activity Bar container with its extension's own icon
 * and delegate rendering here. That delegation gives every OXP
 * extension a fully native VS Code Activity Bar item without the host
 * having to add containers of its own.
 */
export interface OxpHostApi {
  /**
   * Returns a `vscode.WebviewViewProvider` that, when resolved by VS
   * Code, looks the extension up in the OXP store, wires the bridge,
   * and renders the extension's HTML.
   */
  createWebviewProvider(extensionId: string): vscode.WebviewViewProvider;
}

let store: Store;
let grants: Grants;
let runtimeManager: RuntimeManager;
let logChannel: vscode.OutputChannel;
let runtimeRpc: RuntimeRpcService;
let notifyWatcher: fsSync.FSWatcher | undefined;
let extContext: vscode.ExtensionContext;
let switchboard: SwitchboardView;
let explorerSlots: ExplorerSlotManager;

function registry(): string {
  return (
    vscode.workspace.getConfiguration("oxp").get<string>("registry") ??
    "https://oxp.sh"
  );
}

/**
 * Resolve the store root that this VS Code instance reads from.
 *
 * When `oxp.useSharedStore` is true (default) the host points at
 * `$OXP_HOME/host-store` (~/.oxp/host-store) so a single `oxp install`
 * on the command line is reflected in every running IDE. When false
 * we fall back to per-extension globalStorage — useful for isolated
 * test profiles or CI.
 */
function resolveStoreRoot(context: vscode.ExtensionContext): string {
  const cfg = vscode.workspace.getConfiguration("oxp");
  const useShared = cfg.get<boolean>("useSharedStore", true);
  if (!useShared) return context.globalStorageUri.toString();
  const home = process.env.OXP_HOME ?? join(homedir(), ".oxp");
  return vscode.Uri.file(join(home, "host-store")).toString();
}

export function activate(context: vscode.ExtensionContext): OxpHostApi {
  extContext = context;
  const fs = vscodeHostFs();
  const root = resolveStoreRoot(context);
  store = new Store(fs, root);
  grants = new Grants(fs, root);

  logChannel = vscode.window.createOutputChannel("OXP Extensions");
  context.subscriptions.push(logChannel);

  runtimeManager = new RuntimeManager({
    runtime: () => jcoBackend(),
    fs,
    store,
    providerFactory: vscodeProviderFactory(context, logChannel),
    hostName: "vscode",
    hostVersion: vscode.version,
  });

  runtimeRpc = new RuntimeRpcService(logChannel);
  context.subscriptions.push({
    dispose: () => {
      void runtimeRpc.dispose();
    },
  });

  explorerSlots = new ExplorerSlotManager(store, context);
  switchboard = new SwitchboardView(store, explorerSlots);
  context.subscriptions.push(
    vscode.window.registerWebviewViewProvider(SwitchboardView.viewId, switchboard, {
      webviewOptions: { retainContextWhenHidden: true },
    }),
  );
  // Restore Explorer slot context keys immediately so pinned extensions
  // appear in the Explorer as soon as the host activates.
  void explorerSlots.restoreAll();

  // Register the 8 "open in editor" commands for each Explorer slot.
  for (let i = 0; i < 8; i++) {
    const slotId = SLOT_PREFIX + i;
    context.subscriptions.push(
      vscode.commands.registerCommand(`oxp.slot.${i}.open`, async () => {
        const extId = explorerSlots.getExtensionForSlot(slotId);
        if (!extId) return;
        const record = await store.get(extId);
        if (record) await openInstalled(record);
      }),
    );
  }

  const devView = new OxpDevView(context);
  context.subscriptions.push(
    vscode.window.registerWebviewViewProvider(OxpDevView.viewId, devView, {
      webviewOptions: { retainContextWhenHidden: true },
    }),
  );

  // If this window was launched as an Extension Development Host (the
  // developer's window dropped an autostart marker before spawning us),
  // pick it up and start the dev session inline. This mirrors VS Code's
  // F5 EDH UX: the developer keeps editing in their window; this window
  // hosts the running extension.
  void autostartEdhIfMarked(context, devView).then((started) => {
    if (started) {
      void vscode.commands.executeCommand("setContext", "oxp.isEdh", true);
    }
  });

  // Surface a context key so the F5 keybinding only fires inside an
  // OXP project. Re-evaluate when the workspace changes.
  function refreshOxpContext(): void {
    const isOxp = findOxpProjects().length > 0;
    void vscode.commands.executeCommand("setContext", "oxp.isProject", isOxp);
  }
  refreshOxpContext();
  context.subscriptions.push(
    vscode.workspace.onDidChangeWorkspaceFolders(refreshOxpContext),
  );

  // Render extension-driven UI trees and surface status/notify events.
  context.subscriptions.push(
    runtimeRpc.onUiRender((ev) =>
      ExtensionUiPanel.showOrUpdate(runtimeRpc, ev),
    ),
    runtimeRpc.onUiStatus((ev) => {
      logChannel.appendLine(`[ui.status ${ev.extensionId}] ${ev.text}`);
    }),
    runtimeRpc.onUiNotify((ev) => {
      const buttons = ev.buttons.length ? ev.buttons : [];
      void vscode.window.showInformationMessage(
        `[${ev.extensionId}] ${ev.message}`,
        ...buttons,
      );
    }),
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("oxp.install", () => installCommand()),
    vscode.commands.registerCommand("oxp.list", () => listCommand()),
    vscode.commands.registerCommand("oxp.open", (id?: string) =>
      openCommand(id),
    ),
    vscode.commands.registerCommand("oxp.uninstall", (id?: string) =>
      uninstallCommand(id),
    ),
    vscode.commands.registerCommand("oxp.dev", () => devCommand(context)),
    vscode.commands.registerCommand("oxp.devStart", () =>
      startDevSession(context, devView),
    ),
    vscode.commands.registerCommand("oxp.devStop", () => stopDevSession()),
    vscode.commands.registerCommand("oxp.devShowOutput", () => showDevOutput()),
    vscode.commands.registerCommand("oxp.dev.runCommand", () =>
      pickAndRunExtensionCommand(),
    ),
    vscode.commands.registerCommand("oxp.reload", () => reloadCommand()),
    vscode.commands.registerCommand("oxp.activate", (id?: string) =>
      activateCommand(id),
    ),
    vscode.commands.registerCommand("oxp.deactivate", (id?: string) =>
      deactivateCommand(id),
    ),
    vscode.commands.registerCommand("oxp.showLogs", () => logChannel.show()),
    // Rust-runtime path — spawns the oxp-runtime binary and surfaces a
    // webview that loads/activates a wasm component end to end.
    vscode.commands.registerCommand("oxp.runtime.show", () => {
      RuntimePanel.show(runtimeRpc, context);
    }),
    vscode.commands.registerCommand("oxp.runtime.stop", async () => {
      await runtimeRpc.dispose();
      vscode.window.showInformationMessage("OXP runtime stopped.");
    }),
    vscode.commands.registerCommand(
      "oxp.runtime.installFromUrl",
      async (url?: string) => {
        const panel = RuntimePanel.show(runtimeRpc, context);
        if (typeof url === "string" && url.length > 0) {
          await panel.installFromUrl(url);
        } else {
          await panel.installFromUrlInteractive();
        }
      },
    ),
    vscode.commands.registerCommand("oxp.runtime.pickUrlInstall", async () => {
      const panel = RuntimePanel.show(runtimeRpc, context);
      await panel.pickAndActivateUrlInstall();
    }),
  );

  // Watch the shared notify inbox so CLI installs surface immediately
  // in this running VS Code window.
  startNotifyWatcher(context);

  // ── Auto-open already-installed extensions ──
  // On startup, scan ~/.oxp/host-store/ and surface every installed
  // extension that has a UI. This way `oxp install` from *any* terminal
  // (even before this IDE was open) is immediately visible.
  void autoOpenInstalledExtensions();

  // Return the public API consumed by wrapper VSIXes. Generated wrappers
  // call `createWebviewProvider(extensionId)` from their own
  // `activate()` and register the returned provider against their own
  // declared view id. No host-side container or view changes required.
  return {
    createWebviewProvider(extensionId: string): vscode.WebviewViewProvider {
      return new WrapperWebviewProvider(extensionId, store, extContext);
    },
  };
}

export async function deactivate(): Promise<void> {
  // Dispose every running component before VS Code tears down the
  // extension host. Without this the wasm stores leak across reloads.
  notifyWatcher?.close();
  if (runtimeManager) {
    await runtimeManager.disposeAll();
  }
}

/* -------------------------------------------------------------------------- */
/* Cross-process broadcast watcher                                            */
/* -------------------------------------------------------------------------- */

function notifyInboxPath(): string {
  const home = process.env.OXP_HOME ?? join(homedir(), ".oxp");
  return join(home, "notify", "inbox.jsonl");
}

function startNotifyWatcher(context: vscode.ExtensionContext): void {
  const cfg = vscode.workspace.getConfiguration("oxp");
  if (!cfg.get<boolean>("useSharedStore", true)) return;

  const file = notifyInboxPath();
  // Tail the file from end so we only see *new* events, not the backlog.
  let lastSize = 0;
  try {
    lastSize = fsSync.statSync(file).size;
  } catch {
    // file doesn't exist yet — watch the parent dir until it appears.
  }

  const dir = join(file, "..");
  try {
    fsSync.mkdirSync(dir, { recursive: true });
  } catch {
    // ignore
  }

  let pending = false;
  const onChange = (): void => {
    if (pending) return;
    pending = true;
    setTimeout(() => {
      pending = false;
      try {
        const stat = fsSync.statSync(file);
        if (stat.size <= lastSize) {
          lastSize = stat.size;
          return;
        }
        const fd = fsSync.openSync(file, "r");
        try {
          const buf = Buffer.alloc(stat.size - lastSize);
          fsSync.readSync(fd, buf, 0, buf.length, lastSize);
          lastSize = stat.size;
          for (const line of buf.toString("utf8").split(/\r?\n/)) {
            if (!line.trim()) continue;
            try {
              const ev = JSON.parse(line) as {
                kind: string;
                id: string;
                version: string;
              };
              handleNotifyEvent(ev);
            } catch {
              /* malformed line — skip */
            }
          }
        } finally {
          fsSync.closeSync(fd);
        }
      } catch {
        // file vanished or unreadable — try again on next event
      }
    }, 100);
  };

  try {
    notifyWatcher = fsSync.watch(dir, (_event, filename) => {
      if (filename === "inbox.jsonl") onChange();
    });
    context.subscriptions.push({ dispose: () => notifyWatcher?.close() });
  } catch {
    // watch unsupported on this fs (e.g. some network mounts) — fall
    // back to polling so the feature degrades gracefully.
    const interval = setInterval(onChange, 2000);
    context.subscriptions.push({ dispose: () => clearInterval(interval) });
  }
}

function handleNotifyEvent(ev: {
  kind: string;
  id: string;
  version: string;
}): void {
  if (ev.kind !== "installed" && ev.kind !== "updated") return;
  logChannel.appendLine(`[notify] ${ev.kind} ${ev.id}@${ev.version} — opening`);
  // Zero-friction: the user ran `oxp install @x/y` in a terminal — we
  // immediately surface the extension UI in this running window. Focus
  // the OXP activity-bar view so they see it appear, then open the
  // extension's webview/log channel.
  void (async () => {
    try {
      // Reveal the OXP view container so the user sees something animate
      // even before the webview opens.
      await vscode.commands.executeCommand("workbench.view.extension.oxpDev");
    } catch {
      /* view may not exist yet; ignore */
    }
    try {
      const record = await store.get(ev.id);
      if (!record) {
        vscode.window.setStatusBarMessage(
          `OXP: ${ev.id}@${ev.version} installed (open via OXP: List)`,
          5000,
        );
        return;
      }
      const verb = ev.kind === "installed" ? "Installed" : "Updated";
      // Allocate an Explorer slot and make the extension visible
      // immediately — no reload needed.
      await explorerSlots.onExtensionInstalled(record.id);
      const choice = await vscode.window.showInformationMessage(
        `OXP: ${verb} ${record.id}@${record.version}`,
        "Open Now",
        "Reload Window",
      );
      if (choice === "Open Now") {
        await openInstalled(record);
      } else if (choice === "Reload Window") {
        await vscode.commands.executeCommand("workbench.action.reloadWindow");
      }
    } catch (err) {
      logChannel.appendLine(
        `[notify] failed to open ${ev.id}: ${(err as Error).message}`,
      );
    }
  })();
}

async function reloadCommand(): Promise<void> {
  vscode.window.setStatusBarMessage("OXP: store reloaded", 2000);
}

/**
 * Scan the shared install store and surface any already-installed
 * extensions to the user. Instead of silently opening webviews (which
 * would be intrusive on every IDE start), we show a notification that
 * lets the user choose which to open.
 */
async function autoOpenInstalledExtensions(): Promise<void> {
  try {
    const records = await store.list();
    // Refresh the switchboard after the store scan.
    await switchboard.refresh();
    if (records.length === 0) return;

    // Filter to extensions that actually have a UI to show.
    const uiRecords = records.filter((r) => r.manifest.main?.ui);
    if (uiRecords.length === 0) return;

    const names = uiRecords.map(
      (r) => r.manifest.displayName ?? r.id,
    );
    const msg =
      uiRecords.length === 1
        ? `OXP: ${names[0]} is ready`
        : `OXP: ${uiRecords.length} extensions ready (${names.join(", ")})`;

    const choice = await vscode.window.showInformationMessage(
      msg,
      "Open",
      "Show All",
    );
    if (choice === "Open" && uiRecords.length === 1 && uiRecords[0]) {
      await openInstalled(uiRecords[0]);
    } else if (choice === "Open" || choice === "Show All") {
      await listCommand();
    }
  } catch (err) {
    logChannel.appendLine(
      `[auto-open] scan failed: ${(err as Error).message}`,
    );
  }
}

async function installCommand(): Promise<void> {
  const id = await vscode.window.showInputBox({
    title: "OXP: Install Extension",
    prompt: "Enter extension id",
    placeHolder: "@publisher/slug",
    validateInput: (v) =>
      /^@[^/]+\/[^/]+$/.test(v) ? null : "Format: @publisher/slug",
  });
  if (!id) return;

  await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: `Installing ${id}`,
    },
    async (progress) => {
      try {
        progress.report({ message: "resolving + verifying…" });
        const verified = await resolveAndVerify(registry(), id);

        progress.report({ message: "checking permissions…" });
        const { record, prompted } = await finishInstallWithConsent(
          verified,
          store,
          grants,
          vscodePermissionPrompt,
        );
        if (prompted) {
          progress.report({ message: "writing files…" });
        } else {
          progress.report({ message: "writing files…" });
        }

        // Component-v1 / hybrid-v1 → activate immediately.
        if (kindOf(record.manifest) !== "ui-v1") {
          progress.report({ message: "activating component…" });
          try {
            await runtimeManager.activate(record);
          } catch (err) {
            vscode.window.showErrorMessage(
              `Installed ${record.id} but activation failed: ${(err as Error).message}`,
            );
            logChannel.show(true);
            return;
          }
        }

        const buttons: string[] = [];
        if (record.manifest.main?.ui) buttons.push("Open");
        if (kindOf(record.manifest) !== "ui-v1") buttons.push("Show Logs");

        const choice = await vscode.window.showInformationMessage(
          `Installed ${record.id}@${record.version}`,
          ...buttons,
        );
        if (choice === "Open") await openInstalled(record);
        else if (choice === "Show Logs") logChannel.show();
      } catch (err) {
        const msg =
          err instanceof VerifyError
            ? `${err.code}: ${err.message}`
            : (err as Error).message;
        vscode.window.showErrorMessage(`Install failed: ${msg}`);
      }
    },
  );
}

/**
 * Phase A.4 — install-time permission prompt for VS Code.
 *
 * UX flow:
 *   1. Modal warning lists every requested permission. User picks
 *      Allow All / Customize / Deny.
 *   2. "Allow All" grants the full requested set.
 *   3. "Customize" opens a multi-select QuickPick pre-checking the
 *      previously-granted items (or all-checked on a fresh install).
 *   4. "Deny" / dismiss aborts the install with PERMISSION_DENIED_BY_USER.
 *
 * The prompt deliberately does NOT show ambient capabilities
 * (notifications, log, storage) — `buildPromptItems` filters them
 * upstream so the user only sees the things that actually matter.
 */
const vscodePermissionPrompt: PermissionPromptFn = async (req) => {
  const lines = req.items
    .map((it) => {
      const badge =
        it.sensitivity === "sensitive"
          ? " ⚠"
          : it.sensitivity === "install-time"
            ? ""
            : "";
      const scope = it.scope ? ` (${it.scope})` : "";
      const seen = it.previouslyGranted ? " ✓" : "";
      return `  • ${it.description}${scope}${badge}${seen}`;
    })
    .join("\n");
  const heading = req.isUpgrade
    ? `${req.displayName} v${req.version} requests new permissions:`
    : `${req.displayName} v${req.version} requests these permissions:`;
  const choice = await vscode.window.showWarningMessage(
    `${heading}\n\n${lines}\n\nGrant access?`,
    { modal: true },
    "Allow All",
    "Customize",
  );
  if (!choice) return { kind: "deny", reason: "user dismissed prompt" };
  if (choice === "Allow All") {
    return { kind: "grant", grantedRaw: req.items.map((i) => i.raw) };
  }
  // Customize → multi-select QuickPick.
  const picks = await vscode.window.showQuickPick(
    req.items.map((it: PermissionPromptItem) => ({
      label: it.description + (it.scope ? ` (${it.scope})` : ""),
      description: it.capability,
      detail:
        it.sensitivity === "sensitive"
          ? "Sensitive — re-checked on each use"
          : it.sensitivity === "install-time"
            ? "Install-time"
            : "",
      picked: it.previouslyGranted || !req.isUpgrade,
      raw: it.raw,
    })),
    {
      title: `Customize permissions for ${req.displayName}`,
      canPickMany: true,
      ignoreFocusOut: true,
    },
  );
  if (!picks) return { kind: "deny", reason: "user dismissed customize" };
  return { kind: "grant", grantedRaw: picks.map((p) => p.raw) };
};

async function pickInstalled(
  title: string,
): Promise<InstalledRecord | undefined> {
  const records = await store.list();
  if (records.length === 0) {
    vscode.window.showInformationMessage("No OXP extensions installed.");
    return undefined;
  }
  const pick = await vscode.window.showQuickPick(
    records.map((r) => ({
      label: r.id,
      description: r.version,
      detail: `keyId ${r.keyId.slice(0, 24)}…  tar ${r.tarSha256.slice(0, 12)}…  ${
        runtimeManager.isActive(r.id) ? "● running" : "○ stopped"
      }`,
      record: r,
    })),
    { title, matchOnDescription: true, matchOnDetail: true },
  );
  return pick?.record;
}

async function listCommand(): Promise<void> {
  const pick = await pickInstalled("Installed OXP Extensions");
  if (pick) await openInstalled(pick);
}

async function openCommand(id?: string): Promise<void> {
  const record = id
    ? await store.get(id)
    : await pickInstalled("Open OXP Extension");
  if (!record) return;
  await openInstalled(record);
}

async function uninstallCommand(id?: string): Promise<void> {
  const record = id
    ? await store.get(id)
    : await pickInstalled("Uninstall OXP Extension");
  if (!record) return;
  const ok = await vscode.window.showWarningMessage(
    `Uninstall ${record.id}@${record.version}?`,
    { modal: true },
    "Uninstall",
  );
  if (ok !== "Uninstall") return;
  // Deactivate the live component (if any) before deleting files so the
  // wasm store releases its handles to the install dir.
  await runtimeManager.deactivate(record.id);
  await store.uninstall(record.id);
  vscode.window.showInformationMessage(`Uninstalled ${record.id}`);
}

async function activateCommand(id?: string): Promise<void> {
  const record = id
    ? await store.get(id)
    : await pickInstalled("Activate OXP Extension");
  if (!record) return;
  if (kindOf(record.manifest) === "ui-v1") {
    vscode.window.showWarningMessage(
      `${record.id} is a ui-v1 bundle and has no component to activate.`,
    );
    return;
  }
  try {
    await runtimeManager.activate(record);
    vscode.window.showInformationMessage(
      `Activated ${record.id}@${record.version}`,
    );
    logChannel.show(true);
  } catch (err) {
    vscode.window.showErrorMessage(
      `Activation failed: ${(err as Error).message}`,
    );
  }
}

async function deactivateCommand(id?: string): Promise<void> {
  const record = id
    ? await store.get(id)
    : await pickInstalled("Deactivate OXP Extension");
  if (!record) return;
  const ran = await runtimeManager.deactivate(record.id);
  vscode.window.showInformationMessage(
    ran ? `Deactivated ${record.id}` : `${record.id} was not active`,
  );
}

async function openInstalled(record: InstalledRecord): Promise<void> {
  const uiRel = record.manifest.main?.ui;
  if (!uiRel) {
    // Component-only extension — there's no webview to render. Show the
    // log channel instead so the user can see lifecycle output.
    if (kindOf(record.manifest) !== "ui-v1") {
      logChannel.show(true);
      return;
    }
    vscode.window.showWarningMessage(
      `${record.id} has no main.ui — nothing to render`,
    );
    return;
  }

  const surface =
    record.manifest.ui?.preferredSurface === "sidebar"
      ? vscode.ViewColumn.Beside
      : vscode.ViewColumn.Active;

  const resourceRoot = vscode.Uri.parse(store.resourcePath(record));

  const panel = vscode.window.createWebviewPanel(
    "oxp.extension",
    `${record.manifest.displayName ?? record.id}`,
    surface,
    {
      enableScripts: true,
      localResourceRoots: [resourceRoot],
      retainContextWhenHidden: true,
    },
  );

  // Set the tab icon: use the extension's own icon if it declares one,
  // fall back to the OXP sparkle so we never show the generic document icon.
  const iconField = (record.manifest as Record<string, unknown>).icon;
  panel.iconPath = typeof iconField === "string" && iconField
    ? vscode.Uri.joinPath(resourceRoot, ...iconField.split("/"))
    : vscode.Uri.joinPath(extContext.extensionUri, "media", "active-icon.svg");

  // Wire the OXP bridge so `window.oxp.fs.read(...)` etc. work for
  // extensions opened in editor webviews (the fallback path when the
  // wrapper VSIX isn't installed). Wrapper-VSIX-driven views get the
  // same bridge through `createWebviewProvider`.
  const permissions = extractPermissionStrings(record.manifest.permissions);
  const bridgeDisposable = createBridgeHandler(panel.webview, {
    extensionId: record.id,
    version: record.version,
    permissions,
    installDir: store.resourcePath(record),
    context: extContext,
  });
  panel.onDidDispose(() => bridgeDisposable.dispose());

  const outcome = await renderMainUi({
    manifest: record.manifest,
    resourceRoot,
    webview: panel.webview,
    read: async (rel) =>
      vscode.workspace.fs.readFile(
        vscode.Uri.joinPath(resourceRoot, ...rel.split("/")),
      ),
    trusted: true,
  });

  if (outcome.kind === "empty") {
    vscode.window.showErrorMessage(`${record.id}: ${outcome.reason}`);
    panel.dispose();
    return;
  }

  const bridgeJs = loadBridgeScript();
  const bridgeBootstrap = `
<script nonce="${outcome.nonce}">
  (function() {
    var vscode = acquireVsCodeApi();
    window.__vscode = vscode;
    window.__oxp_extension_id = ${JSON.stringify(record.id)};
    window.__oxp_extension_version = ${JSON.stringify(record.version)};
  })();
</script>
<script nonce="${outcome.nonce}">${bridgeJs}</script>`;

  let html = outcome.html;
  if (/<\/head>/i.test(html)) {
    html = html.replace(/<\/head>/i, `${bridgeBootstrap}</head>`);
  } else {
    html = bridgeBootstrap + html;
  }
  panel.webview.html = html;
}
